name: Build and Deploy to Neocities

on:
  push:
  workflow_dispatch:

env:
  NEOCITIES_API_KEY: ${{ secrets.NEOCITIES_API_KEY }}

jobs:
  build:
    runs-on: native
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          path: source

      - name: Checkout Chobble Template
        uses: actions/checkout@v4
        with:
          repository: chobble/chobble-template
          ref: main
          path: template

      - name: Get Eleventy .cache
        uses: actions/cache/restore@v4
        with:
          path: .image-cache
          key: eleventy-img-cache
          fail-on-cache-miss: false

      - name: Make combined dir
        run: mkdir combined

      - name: Copy template files to combined dir
        run: |
          rsync \
            --recursive \
            --verbose \
            --no-perms \
            --chmod=ugo=rwX \
            --delete \
            --exclude=".git" \
            --exclude="node_modules" \
            --exclude="*.md" \
            template/ \
            combined/

      - name: Overlay our repo files into combined src
        run: |
          rsync \
            --recursive \
            --verbose \
            --exclude=".git" \
            --exclude="*.nix" \
            --exclude="README.md" \
            --exclude=".forgejo" \
            --exclude=".image-cache" \
            source \
            combined/src/

      - name: Copy .image-cache folder in separately
        run: |
          rsync \
            --recursive \
            --no-perms \
            --chmod=ugo=rwX \
            --include="*.jpeg" \
            --include="*.webp" \
            source/.image-cache \
            combined/

      - name: Make Forgejo cache dir
        run: mkdir -p .image-cache

      - name: Copy Forgejo cache into combined dir
        run: |
          rsync \
            --recursive \
            --no-perms \
            --chmod=ugo=rwX \
            --include="*.jpeg" \
            --include="*.webp" \
            .image-cache \
            combined/

      - name: Update site.json with secrets
        run: |
          sed -i \
            's/"formspark_id": null/"formspark_id": "${{ secrets.FORMSPARK_ID }}"/g' \
            "combined/src/_data/site.json"
          sed -i \
            's/"botpoison_public_key": null/"botpoison_public_key": "${{ secrets.BOTPOISON_PUBLIC_KEY }}"/g' \
            "combined/src/_data/site.json"

      - name: Fix permissions
        run: |
          find combined -type d -exec chmod 755 {} \;
          find combined -type f -exec chmod 644 {} \;

      - name: List build dir
        run: |
          echo $(ls -al combined)
          echo $(ls -al combined/.image-cache)

      - name: Build with Nix
        id: build
        run: |
          cd combined
          nix-fast-build \
            --skip-cached \
            --flake ".#packages.x86_64-linux.site" \
            --no-nom

      - name: Copy .image-cache out of result
        run: |
          rsync -a \
            --delete \
            --include="*.jpeg" \
            --include="*.webp" \
            result-/.image-cache \
            .image-cache

      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: .image-cache
          key: eleventy-img-cache

      - name: Copy built site out of result
        run: |
          mkdir built-site
          rsync -a \
            --exclude=".image-cache" \
            result-/ \
            built-site/

      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v3
        with:
          api_key: ${{ secrets.NEOCITIES_API_KEY }}
          cleanup: true
          neocities_supporter: true
          preview_before_deploy: false
          dist_dir: "built-site"

      - name: Deploy to Bunny
        uses: R-J-dev/bunny-deploy@v2.0.6
        with:
          access-key: ${{ secrets.BUNNY_ACCESS_KEY }}
          directory-to-upload: built-site
          storage-endpoint: "https://storage.bunnycdn.com"
          storage-zone-name: "chobble-tradesperson-example"
          storage-zone-password: ${{ secrets.BUNNY_STORAGE_ZONE_PASSWORD }}
          concurrency: "5"
          enable-delete-action: true
          enable-purge-pull-zone: true
          pull-zone-id: "3573523"
          replication-timeout: "15000"

      - name: Remove result and fix permissions
        run: |
          rm -rf result-
          find . -type d -exec chmod 755 {} \;
          find . -type f -exec chmod 644 {} \;
